WEB_HM_10/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

WEB_HM_10/quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.autor, name='author'),
    path('authorspage/', views.author_page, name='authors_page'),
    path('quotesspage/', views.quotes_page, name='quotes_page'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('done/<int:quote_id>', views.set_done, name='set_done'),
    path('delete/<int:quote_id>', views.delete_note, name='delete'),
]

WEB_HM_10/quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

WEB_HM_10/quotes/quotesapp/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=250, null=False, unique=True)
    born_date = models.CharField(max_length=250)
    born_location = models.CharField(max_length=250, null=False, unique=False)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=250, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

   




  

WEB_HM_10/quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Author, Quote


class AutorForm(ModelForm):

    name = CharField(min_length=3, max_length=25,
                     required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname']


class QuoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50,
                     required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150,
                            required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['name', 'description']
        exclude = ['authors']

WEB_HM_10/quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AutorForm, QuoteForm
from .models import Author, Quote
from .utils import get_mongo_db
from django.core.paginator import Paginator

# Create your views here.


def main(request):
    quotes = Quote.objects.all()
    return render(request, "quotesapp/index.html", context={"quotes": quotes})


def author_page(request):
    author = Author.objects.all()
    return render(request, "quotesapp/authors_page.html", {"authors": author})


def quotes_page(request):
    quote = Quote.objects.all()
    return render(request, "quotesapp/quotes_page.html", {"quotes": quote})


def autor(request):
    if request.method == "POST":
        form = AutorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/author.html", {"form": form})

    return render(request, "quotesapp/author.html", {"form": AutorForm()})


def quote(request):
    authors = Author.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_authors = Author.objects.filter(
                name__in=request.POST.getlist("authors")
            )
            for author in choice_authors.iterator():
                new_quote.authors.add(author)

            return redirect(to="quotesapp:main")
        else:
            return render(
                request, "quotesapp/quotes.html", {"authors": authors, "form": form}
            )

    return render(
        request, "quotesapp/quotes.html", {"authors": authors, "form": QuoteForm()}
    )


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, "quotesapp/detail.html", {"quote": quote})


def set_done(request, quote_id):
    Quote.objects.filter(pk=quote_id).update(done=True)
    return redirect(to="quotesapp:main")


def delete_note(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to="quotesapp:main")

WEB_HM_10/quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

WEB_HM_10/quotes/quotesapp/templates/quotesapp/author_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Author Page</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
</head>

<body>
    <main class="container">
        <h1>Author Details</h1>
        <p>Author Name: {{ author.name }}</p>
        <!-- Дополнительная информация об авторе, если необходимо -->
        <!-- Пример: <p>Author Bio: {{ author.bio }}</p> -->

        <!-- Ссылка для возврата на главную страницу или другую страницу по вашему выбору -->
        <a href="{% url 'main_page' %}">Back to Main Page</a>
    </main>
</body>

</html>

WEB_HM_10/quotes/quotesapp/templates/quotesapp/authors_page.html
{% extends "quotesapp/base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Authors Page</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
</head>

<body>
    <main class="container">
        {% for author in authors%}
        <div class="author" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ author.fullname }}
            </span>
            
        </div>
        {% endfor %}
        </div>
    </main>
</body>

</html>
{% endblock %}

WEB_HM_10/quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

WEB_HM_10/quotes/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %} {% load extract_authors %} {% block content %}

<h1>{{quote.name}}</h1>
<p>Description: <b>{{quote.description}}</b></p>
<p>Time of creation: <kbd>{{quote.created}}</kbd></p>
{% if quote.done %}
<p>
    Status:
    <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}
<p>Author: <small> {{ quote.authors|authors }} </small></p>
{% endblock %}

WEB_HM_10/quotes/quotesapp/templates/quotesapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quotesapp:quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quotesapp:author' %}" role="button">Add Author</a></li>
                <li><a href="{% url 'quotesapp:authors_page' %}" role="button">View Authors</a></li>
                <li><a href="{% url 'quotesapp:quotes_page' %}" role="button">View Quotes</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                <li><a href="{% url 'quotesapp:authors_page' %}" role="button">View Authors</a></li>
                <li><a href="{% url 'quotesapp:quotes_page' %}" role="button">View Quotes</a></li>
            </ul>
            {% endif %}
            
            </nav>

    
    </main>
</body>

</html>

WEB_HM_10/quotes/quotesapp/templates/quotesapp/quotes.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

WEB_HM_10/quotes/quotesapp/templates/quotesapp/quotes_page.html
{% extends "quotesapp/base.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/quotespage.css' %}">
    <!-- Подключаем стили от pico.css -->
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="row">
                <div class="col-md-8">
            
                    {% for quote in quotes%} 
                    
                    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                        <span class="text" itemprop="text">
                            {{ quote.quote }}
                        <span>
                        <span>
                            by 
                            <small class="author" itemprop="author">
                                {{ quote.author.fullname }}
                            </small> <a href="/author/{{ quote.author.fullname }}"></a></span>
                        </div>
                    </div>
                    {% endfor %}
            
                </div>
        </div>


        <div class="row">
            <div class="col-md-8">

                

                <nav>
                    <ul class="pager">


                        <li class="next">
                            <a href="/page/2/">Next <span aria-hidden="true">→</span></a>
                        </li>

                    </ul>
                </nav>
            </div>
            
        </div>

    
    </footer>

</body>
{% endblock %}